name: test

on:
  push:
    branches: [main] # pushes TO main
  pull_request:
    branches: [main] # pull requests AGAINST main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
        - '1.21'
        - '1.20'
        - '1.19'

    steps:
    - name: setup
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.go-version}}

    - name: checkout
      uses: actions/checkout@v4

    - name: test
      run: make testci

    - name: report code coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.out
      if: ${{ matrix.go-version == '1.21' }}
