name: test

on:
  push:
    branches: [main] # pushes TO main
  pull_request:
    branches: [main] # pull requests AGAINST main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
        - stable
        - oldstable

    steps:
    - name: setup
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{matrix.go-version}}

    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: test
      run: make testci

    - name: report code coverage
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
      with:
        files: ./coverage.out
      if: ${{ matrix.go-version == 'stable' }}
