name: test

on:
  push:
    branches: [main] # pushes TO master
  pull_request:
    branches: [main] # pull requests AGAINST master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
        - '1.17'
        - '1.16'
        - '1.15'

    steps:
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go-version}}

    - name: checkout
      uses: actions/checkout@v2

    - name: test
      run: make testci

    - name: report code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
      if: ${{ matrix.go-version == '1.17' }}
